"""empty message

Revision ID: 2e9066c13080
Revises: 
Create Date: 2021-12-28 14:17:32.527419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e9066c13080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
