"""empty message

Revision ID: 54172695f37f
Revises: 1638e7da0c98
Create Date: 2022-01-05 14:41:16.562067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54172695f37f'
down_revision = '1638e7da0c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
